# Generated by Django 5.2.9 on 2025-12-14 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('track_id', models.CharField(max_length=80, unique=True)),
                ('track_name', models.CharField(max_length=300)),
                ('track_number', models.PositiveIntegerField()),
                ('track_popularity', models.PositiveIntegerField()),
                ('explicit', models.BooleanField()),
                ('artist_name', models.CharField(max_length=300)),
                ('artist_popularity', models.PositiveIntegerField()),
                ('artist_followers', models.BigIntegerField()),
                ('artist_genres', models.TextField(blank=True, null=True)),
                ('album_id', models.CharField(max_length=80)),
                ('album_name', models.CharField(max_length=300)),
                ('album_release_date', models.DateField()),
                ('album_total_tracks', models.PositiveIntegerField()),
                ('album_type', models.CharField(max_length=50)),
                ('track_duration_min', models.FloatField()),
            ],
        ),
    ]
